### ISSUE TITLE
[feedback] Goodjob

### ISSUE THREAD

**Issue by Ramon96** [TomasS666/frontend-applications#11]
goodjob men, you are really making the most of it. 
I know that you are really tired and busy but nevertheless your quality isn't suffering from it. 
Goodjob buddy, you are really in the final stretch now.

you can do it! 👍

**Comment by TomasStolp** [comment]
Thanks mate, we're gonna talk and get wasted soon! Thanks for all the support!! I'm not staying in the monkey.
